### ISSUE TITLE
A crash on startup

### ISSUE THREAD

**Issue by birdie-github** [WayfireWM/wf-shell#190]
```
Thread 1 "wf-panel" received signal SIGSEGV, Segmentation fault.
0x00007ffff7eb3028 in wl_proxy_add_listener (proxy=0x3, implementation=0x5555556080c0 <toplevel_manager_v1_impl>, 
    data=0x555555881700) at ../src/wayland-client.c:613
Downloading source file /usr/src/debug/wayland-1.22.0-1.fc38.x86_64/redhat-linux-build/../src/wayland-client.c
613             if (proxy->flags & WL_PROXY_FLAG_WRAPPER)                                                               
(gdb) bt
#0  0x00007ffff7eb3028 in wl_proxy_add_listener
    (proxy=0x3, implementation=0x5555556080c0 <toplevel_manager_v1_impl>, data=0x555555881700)
    at ../src/wayland-client.c:613
#1  0x00005555555bce2f in zwlr_foreign_toplevel_manager_v1_add_listener
    (data=0x555555881700, listener=0x5555556080c0 <toplevel_manager_v1_impl>, zwlr_foreign_toplevel_manager_v1=<optimized out>) at src/panel/wf-panel.p/wlr-foreign-toplevel-management-unstable-v1-client-protocol.h:144
#2  WayfireWindowList::init(Gtk::HBox*) (this=0x555555881700, container=0x5555556f1548)
    at ../src/panel/widgets/window-list/window-list.cpp:189
#3  0x000055555559a2bd in WayfirePanel::impl::reload_widgets(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::vector<std::unique_ptr<WayfireWidget, std::default_delete<WayfireWidget> >, std::allocator<std::unique_ptr<WayfireWidget, std::default_delete<WayfireWidget> > > >&, Gtk::HBox&) (this=<optimized out>, list=Python Exception <class 'gdb.error'>: value has been optimized out

   , container=<optimized out>, box=<optimized out>) at ../src/panel/panel.cpp:275
#4  0x000055555559dee2 in WayfirePanel::impl::init_widgets() (this=0x5555556f14f0) at ../src/panel/panel.cpp:305
#5  WayfirePanel::impl::create_window() (this=0x5555556f14f0) at ../src/panel/panel.cpp:133
#6  WayfirePanel::impl::impl(WayfireOutput*)
    (this=0x5555556f14f0, output=<optimized out>, this=<optimized out>, output=<optimized out>)
    at ../src/panel/panel.cpp:313
#7  0x000055555559e640 in WayfirePanel::WayfirePanel(WayfireOutput*) (output=0x5555557f84e0, this=0x5555557d57a0)
    at ../src/panel/panel.cpp:345
#8  WayfirePanelApp::handle_new_output(WayfireOutput*) (this=0x55555562f060, output=0x5555557f84e0)
    at ../src/panel/panel.cpp:379
#9  0x00005555555d0201 in WayfireShellApp::on_activate() (this=0x55555562f060) at ../src/util/wf-shell-app.cpp:126
#10 0x00007ffff6d05654 in sigc::slot0<void>::operator()() const (this=0x5555557312c8)
--Type <RET> for more, q to quit, c to continue without paging--
    at /usr/include/sigc++-2.0/sigc++/functors/slot.h:535
#11 Glib::SignalProxyNormal::slot0_void_callback(_GObject*, void*) (self=<optimized out>, data=0x5555557312c0) at ../glib/glibmm/signalproxy.cc:103
#12 0x00007ffff6b1f4ea in g_closure_invoke (closure=0x5555556669f0, return_value=0x0, n_param_values=1, param_values=0x7fffffffd750, invocation_hint=0x7fffffffd6d0)
    at ../gobject/gclosure.c:832
#13 0x00007ffff6b4de16 in signal_emit_unlocked_R.isra.0
    (node=node@entry=0x555555690fe0, detail=detail@entry=0, instance=instance@entry=0x5555556921a0, emission_return=emission_return@entry=0x0, instance_and_params=instance_and_params@entry=0x7fffffffd750) at ../gobject/gsignal.c:3812
#14 0x00007ffff6b3ecbd in g_signal_emit_valist (instance=<optimized out>, signal_id=<optimized out>, detail=<optimized out>, var_args=var_args@entry=0x7fffffffd8f0)
    at ../gobject/gsignal.c:3565
#15 0x00007ffff6b3ef33 in g_signal_emit (instance=<optimized out>, signal_id=<optimized out>, detail=<optimized out>) at ../gobject/gsignal.c:3622
#16 0x00007ffff7907519 in sigc::slot1<void, Glib::ustring const&>::operator()(Glib::ustring const&) const (_A_a1=..., this=0x555555941558)
    at /usr/include/sigc++-2.0/sigc++/functors/slot.h:665
#17 (anonymous namespace)::Application_signal_command_line_notify_callback(GApplication*, GApplicationCommandLine*, void*)
    (self=self@entry=0x5555556921a0, p0=0x555555810220, data=0x555555941550) at ../untracked/gio/giomm/application.cc:593
#18 0x00007ffff6daeee0 in _g_cclosure_marshal_INT__BOXED
    (closure=0x55555592c050, return_value=0x7fffffffdb90, param_values=0x7fffffffdbf0, marshal_data=<optimized out>, invocation_hint=<optimized out>, n_param_values=<optimized out>) at ../gio/gmarshal-internal.c:714
#19 0x00007ffff6b1f4ea in g_closure_invoke
    (closure=0x55555592c050, return_value=0x7fffffffdb90, n_param_values=2, param_values=0x7fffffffdbf0, invocation_hint=0x7fffffffdb70) at ../gobject/gclosure.c:832
#20 0x00007ffff6b4de16 in signal_emit_unlocked_R.isra.0
    (node=<optimized out>, detail=detail@entry=0, instance=instance@entry=0x5555556921a0, emission_return=emission_return@entry=0x7fffffffdd00, instance_and_params=instance_and_params@entry=0x7fffffffdbf0) at ../gobject/gsignal.c:3812
#21 0x00007ffff6b3e7e2 in g_signal_emit_valist (instance=<optimized out>, signal_id=<optimized out>, detail=<optimized out>, var_args=var_args@entry=0x7fffffffddb0)
    at ../gobject/gsignal.c:3575
#22 0x00007ffff6b3ef33 in g_signal_emit (instance=instance@entry=0x5555556921a0, signal_id=<optimized out>, detail=detail@entry=0) at ../gobject/gsignal.c:3622
#23 0x00007ffff6e168fb in g_application_call_command_line (exit_status=0x7fffffffdf94, options=0x555555779640, arguments=<optimized out>, application=0x5555556921a0)
    at ../gio/gapplication.c:1084
#24 g_application_call_command_line (application=0x5555556921a0, arguments=<optimized out>, options=0x555555779640, exit_status=0x7fffffffdf94)
    at ../gio/gapplication.c:1062
#25 0x00007ffff6e19e51 in g_application_real_local_command_line (application=0x5555556921a0, arguments=0x7fffffffdf98, exit_status=0x7fffffffdf94)
    at ../gio/gapplication.c:1139
#26 0x00007ffff6e19fb3 in g_application_run (application=0x5555556921a0, argc=<optimized out>, argv=0x7fffffffe148) at ../gio/gapplication.c:2542
#27 0x0000555555592071 in WayfirePanelApp::create(int, char**) (argv=0x7fffffffe148, argc=1) at ../src/panel/panel.cpp:418
#28 main(int, char**) (argc=1, argv=0x7fffffffe148) at ../src/panel/panel.cpp:428
```

Using Fedora 38 packages:
```
wf-shell-0.8.0-1.fc38.x86_64                  Mon 16 Oct 2023 08:44:48 AM UTC
wf-config-0.8.0-1.fc38.x86_64                 Mon 16 Oct 2023 08:44:48 AM UTC
wayfire-config-manager-0.8.0-1.fc38.x86_64    Mon 16 Oct 2023 08:44:48 AM UTC
wayfire-0.8.0-2.fc38.x86_64                   Mon 16 Oct 2023 08:44:48 AM UTC
```

**Comment by nunez-dev** [comment]
I also see this on Arch. I tried the default wf-shell.ini config + moving back from wf-shell-git and can still repro.
```
yay -Q wayfire wf-shell wf-config
wayfire 0.8.0-3
wf-shell 0.8.0-1
wf-config 0.8.0-3
```
Not using debug libs but same trace.
```
#0  0x00007ffff7ea2728 in wl_proxy_add_listener () at /usr/lib/libwayland-client.so.0
#1  0x00005555555b61a5 in  ()
#2  0x0000555555593777 in  ()
#3  0x0000555555597337 in  ()
#4  0x0000555555597acf in  ()
#5  0x00005555555cc0d0 in  ()
#6  0x00007ffff6d0089d in Glib::SignalProxyNormal::slot0_void_callback(_GObject*, void*) () at /usr/lib/libglibmm-2.4.so.1
#7  0x00007ffff6b1e6c0 in g_closure_invoke () at /usr/lib/libgobject-2.0.so.0
#8  0x00007ffff6b4ca36 in  () at /usr/lib/libgobject-2.0.so.0
#9  0x00007ffff6b3da42 in  () at /usr/lib/libgobject-2.0.so.0
#10 0x00007ffff6b3dc77 in g_signal_emit_valist () at /usr/lib/libgobject-2.0.so.0
#11 0x00007ffff6b3dd34 in g_signal_emit () at /usr/lib/libgobject-2.0.so.0
#12 0x00007ffff7905457 in  () at /usr/lib/libgiomm-2.4.so.1
#13 0x00007ffff6da2e99 in  () at /usr/lib/libgio-2.0.so.0
#14 0x00007ffff6b1e6c0 in g_closure_invoke () at /usr/lib/libgobject-2.0.so.0
#15 0x00007ffff6b4ca36 in  () at /usr/lib/libgobject-2.0.so.0
#16 0x00007ffff6b3d335 in  () at /usr/lib/libgobject-2.0.so.0
#17 0x00007ffff6b3dc77 in g_signal_emit_valist () at /usr/lib/libgobject-2.0.so.0
#18 0x00007ffff6b3dd34 in g_signal_emit () at /usr/lib/libgobject-2.0.so.0
#19 0x00007ffff6e0a2f7 in  () at /usr/lib/libgio-2.0.so.0
#20 0x00007ffff6e0d92b in  () at /usr/lib/libgio-2.0.so.0
#21 0x00007ffff6e0da8c in g_application_run () at /usr/lib/libgio-2.0.so.0
#22 0x000055555558b54c in main ()
```
It doesn't crash every time on startup, but most times. It believe it started appearing after "upgraded wayfire (0.7.5-1 -> 0.8.0-2)"

**Comment by ammen99** [comment]
Have you enabled the foreign-toplevel plugin in Wayfire 0.8.0?

**Comment by nunez-dev** [comment]
Thanks for tip, I enabled wayfire-shell, foreign-toplevel, and gtk-shell as per the patch notes and it is no longer crashing.

**Comment by ammen99** [comment]
@nunez-dev PR #195 should also fix the crash when foreign-toplevel is not enabled (but of course, in this case window-list will not work).
